### ISSUE TITLE
[P1] Contact information

### ISSUE THREAD

**Issue by automateyournetwork** [stanfordnlp/pyreft#116]
Hey I would love to get in touch with your team to share of my implementation of your work! It's remarkable!

**Comment by frankaging** [comment]
Hey @automateyournetwork! Thanks for your interests! This repo is maintained by the authors on [our paper](https://arxiv.org/abs/2404.03592).

You could reach out to us at Zhengxuan Wu <wuzhengx@stanford.edu> and Aryaman Arora <aryamana@stanford.edu>.
