### ISSUE TITLE
[P1] Reproducing commonsense results

### ISSUE THREAD

**Issue by jacknewsom** [stanfordnlp/pyreft#124]
Hello,

Am I correct in understanding that you do not use the 'passage' field in BoolQ at all? It looks like [commonsense_170k.json](https://github.com/AGI-Edgerunners/LLM-Adapters/blob/main/ft-training_set/commonsense_170k.json) does not actually contain a 'passage' for any entry.

![image](https://github.com/user-attachments/assets/d3fe15fd-9d8b-460a-b5fe-4b786a6ef046)

**Comment by frankaging** [comment]
@jacknewsom Thanks for the question. You are right - no retrieved or golden passages are used in our case, and the same thing applies to [LLM-Adaptors](https://github.com/AGI-Edgerunners/LLM-Adapters) eval, i think. We will add a sentence to the appendix to clarify this.

**Comment by frankaging** [comment]
Appendix updated. 
<img width="605" alt="Screenshot 2024-07-30 at 1 41 13 PM" src="https://github.com/user-attachments/assets/f1c1c68b-1a1c-4ee3-b4a9-a62bc5c4c2a4">

Closing this ticket for now. The updated draft will be released with other updates later.
