### ISSUE TITLE
[P1] About DPO training

### ISSUE THREAD

**Issue by hz0567** [stanfordnlp/pyreft#127]
Hi, I tried to reproduce the dpo notebook. The completion on the question 'What does ADIDAS stand for?' runned by myself is differnt from the notebook. From my experiment, the reft model answered almost the same thing compared with the orginal model. Also, I found that the reward ranking accuracy during the dpo training runned by myself is always 100% on TruthfulQA dataset. Is there any problem with that ? I did not modify any scripts provided in the example.

**Comment by frankaging** [comment]
@HongzhengYang Hey, could you pull from the ToT main branch, and try again? Thanks to @AmirZur, the fix is checked in.
