### ISSUE TITLE
[P1] Unable to access gradients of intervention blocks

### ISSUE THREAD

**Issue by m-dev12** [stanfordnlp/pyreft#135]
Hi @frankaging ,

This is not an issue, but a question. I am trying to access the gradients w.r..t the intervention blocks using the code below. I am able to access the classifer head gradients but the gradients w.r.t the intervention weights always show up to be none.

<img width="1191" alt="Screenshot 2024-09-07 at 6 40 42 PM" src="https://github.com/user-attachments/assets/7efba378-fc02-4c27-9308-0cbff6be623e">

Have you done this in the past, or if you could help out if you are aware?

Thanks!

**Comment by frankaging** [comment]
@m-dev12 Hey, thanks for the q. What is your reft config? and could you show one example of your forward call (e.g., with inputs)?
