### ISSUE TITLE
Support Llama 3.1

### ISSUE THREAD

**Issue by lyy1994** [stanfordnlp/pyreft#137]
Hi, it seems that `pyvene` has a strict dependency on `transformers==4.40.2`. This old version cannot load the latest Llama 3.1 models. Could you bump the version to support training Llama 3.1?

**Comment by explanare** [comment]
We have updated the `transformers` library version to 4.45.1 in [stanfordnlp/pyvene/#189](https://github.com/stanfordnlp/pyvene/pull/189).
