### ISSUE TITLE
evaluate 

### ISSUE THREAD

**Issue by jeaneigsi** [stanfordnlp/pyreft#34]
Fix `ModuleNotFoundError: No module named 'evaluate'` after`  !pip install git+https://github.com/frankaging/pyreft.git `by adding this step : `!pip install evaluate `in the readme. It's raised a error that can cause a disgreements to the user.

**Comment by frankaging** [comment]
ty! `requirements.txt` is updated! i also updated README to show verified conda env setup. it should work now with a from-scratch conda env with python3.10.
