### ISSUE TITLE
[P1] Lots of dependency issues.

### ISSUE THREAD

**Issue by Akshaysharma29** [stanfordnlp/pyreft#35]
Hi Team, thanks for coming up with this wonderful work. I love it. but while trying to replicate this on GPU I am facing many compatibility issues 

`Command: pip install -r requirements.txt
`
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf 23.8.0 requires cubinlinker, which is not installed.
cudf 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
cudf 23.8.0 requires ptxcompiler, which is not installed.
cuml 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
dask-cudf 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
apache-beam 2.46.0 requires dill<0.3.2,>=0.3.1.1, but you have dill 0.3.8 which is incompatible.
apache-beam 2.46.0 requires numpy<1.25.0,>=1.14.3, but you have numpy 1.26.4 which is incompatible.
apache-beam 2.46.0 requires pyarrow<10.0.0,>=3.0.0, but you have pyarrow 15.0.2 which is incompatible.
beatrix-jupyterlab 2023.128.151533 requires jupyterlab~=3.6.0, but you have jupyterlab 4.1.5 which is incompatible.
cudf 23.8.0 requires cuda-python<12.0a0,>=11.7.1, but you have cuda-python 12.4.0 which is incompatible.
cudf 23.8.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.1.4 which is incompatible.
cudf 23.8.0 requires protobuf<5,>=4.21, but you have protobuf 3.20.3 which is incompatible.
cudf 23.8.0 requires pyarrow==11.*, but you have pyarrow 15.0.2 which is incompatible.
cuml 23.8.0 requires dask==2023.7.1, but you have dask 2024.3.1 which is incompatible.
dask-cuda 23.8.0 requires dask==2023.7.1, but you have dask 2024.3.1 which is incompatible.
dask-cuda 23.8.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.1.4 which is incompatible.
dask-cudf 23.8.0 requires dask==2023.7.1, but you have dask 2024.3.1 which is incompatible.
dask-cudf 23.8.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.1.4 which is incompatible.
distributed 2023.7.1 requires dask==2023.7.1, but you have dask 2024.3.1 which is incompatible.
gcsfs 2023.12.2.post1 requires fsspec==2023.12.2, but you have fsspec 2024.2.0 which is incompatible.
raft-dask 23.8.0 requires dask==2023.7.1, but you have dask 2024.3.1 which is incompatible.
s3fs 2024.3.0 requires fsspec==2024.3.0, but you have fsspec 2024.2.0 which is incompatible.
ydata-profiling 4.6.4 requires numpy<1.26,>=1.16.0, but you have numpy 1.26.4 which is incompatible.
ydata-profiling 4.6.4 requires seaborn<0.13,>=0.10.1, but you have seaborn 0.13.2 which is incompatible.
```

can you update your requiremnts.txt file?
Thanks

**Comment by aryamanarora** [comment]
@Akshaysharma29 Thanks for filing the issue! Is this in a fresh env (through conda or pyenv or some other environment manager) and do you already have the appropriate `torch` set up for your cuda version? We are aware of reqs issues so I'll try seeing if this happens in a fresh env.

**Comment by Akshaysharma29** [comment]
Hi @aryamanarora Thanks for the quick response. I was trying it to set up on Kaggle p100 notebook.

**Comment by Akshaysharma29** [comment]
@aryamanarora let me know if any help required from my side :)

**Comment by aryamanarora** [comment]
@Akshaysharma29 Hey! I experimented with installation on a Kaggle P100. I think many of these issues don't have to do with installation of `pyreft` but rather existing libraries on the machine; still, I relaxed the `torch` req and dropped `seaborn`.

`import pyreft` runs without errors even though those warnings show up. Can you trying importing the library on your end?

I can also downgrade the `numpy` req without issues I think, may remove a few more warnings.

**Comment by Akshaysharma29** [comment]
Hi @aryamanarora, Can you share your notebook? I have tried but facing the same issue, I have also tried to `import pyreft` as well in spite of errors but facing the below issue.

```
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/opt/conda/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

```

**Comment by frankaging** [comment]
hey @Akshaysharma29 after all the pip install, could you try

(1) `!pip install fsspec==2024.3.0`
(2) restart your notebook? (like in attached screen-shot)

<img width="1434" alt="Screenshot 2024-04-08 at 2 02 56 AM" src="https://github.com/stanfordnlp/pyreft/assets/15223704/f03f85d7-2f30-4194-89f8-8b9927ead7de">

**Comment by Akshaysharma29** [comment]
Hi @frankaging, facing the same error but Yes it is working now :)  . Thank you
One more issue is that I wanted to use it with the internet off. so I need to download it  using `!pip download -q git+https://github.com/frankaging/pyreft.git  -d ./pyreft/` and then pip install in other notebook file using `!pip install pyreft`
Can you help me resolve that?

It is generally working the file which can be install using pip. Example `pip install pandas`.

**Comment by frankaging** [comment]
update: i think you can run this
`!pip install git+https://github.com/stanfordnlp/pyreft.git` with internet on. it should run without any error now.

![Uploading Screenshot 2024-04-08 at 3.47.40 PM.png…]()

**Comment by frankaging** [comment]
closing this ticket for now. feel free to reopen if there are other blocking warnings! thanks for reporting the issue!
