### ISSUE TITLE
[P0] reft_model loading as reft_model not as pyvene object

### ISSUE THREAD

**Issue by Jixs0528** [stanfordnlp/pyreft#45]
A reft_model got by the method _get_reft_model()_ is an instance of **ReftModel** and we can call the method _print_trainable_parameters()_ to show the number of parameters. However, a reft_model  loaded by the method _ReftModel.load()_ is an instance of **intervenable_base.IntervenableModel** and we can not call the method _print_trainable_parameters()_. Is this 
reasonable?

**Comment by frankaging** [comment]
@Jixs0528 good catch! this should be fixed!

**Comment by PinetreePantry** [comment]
@frankaging cool let me take a look

**Comment by frankaging** [comment]
Fixed! closing this for now. Feel free to reopen if other issues arise. Ty for raising this again.

**Comment by Jixs0528** [comment]
I think the method _forward()_ in the class **NoreftIntervention** should be:
```
output = base + torch.matmul(
            (self.act_fn(self.learned_source(base)) - proj_base), self.proj_layer.weight.T
        )
```
Or it will raise a RuntimeError.

**Comment by frankaging** [comment]
hey @Jixs0528 can you provide the error log? **NoreftIntervention** runs fine on my end.

**Comment by frankaging** [comment]
<img width="378" alt="Screenshot 2024-04-12 at 1 38 08 AM" src="https://github.com/stanfordnlp/pyreft/assets/15223704/694e5423-64b2-4a56-ad2b-c03606c6dfd6">

providing more evidence here. the weight matrix in **NoreftIntervention** is initialized with (model_dim, low_rank_dim). the weight matrix is in a shape of (low_rank_dim*model_dim).

**Comment by Jixs0528** [comment]
@frankaging Sorry. I misunderstood the shape of proj_layer.weight. Thanks for replying quickly.
