### ISSUE TITLE
[P1] ReFT+PEFT by using ReftModel to wrap PeftModel

### ISSUE THREAD

**Issue by frankaging** [stanfordnlp/pyreft#46]
**Descriptions:**

By taking a quick look at the PEFT library, it wraps nn.module as a PEFT nn.module which accepts gradient, is trainable, and just like another nn.module. This is highly compatible with ReFT.

We should make ReFT also to support any PEFT model as well. It might work out-of-the-box already. This ticket will track a validation effort. For instance, checking whether trainable parameter prints the correct one when we add LoReFT + LoRA.

**Comment by frankaging** [comment]
providing more notes here:

1. getting the `peft` model:
```py
peft_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM, inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1
)

model = AutoModelForSeq2SeqLM.from_pretrained(model_name_or_path)
peft_model = get_peft_model(model, peft_config)
```

2. getting the `reft_on_peft_model` model:
```py
reft_config = ReftConfig(representations={
    "component": f"model.layers[15].output", # string access to the model component
    "intervention": ConsreftIntervention(
    embed_dim=model.config.hidden_size, low_rank_dimension=1)})

reft_on_peft_model = get_reft_model(peft_model, reft_config)
reft_on_peft_model.print_trainable_parameters()
```

**Comment by Vikrant-Khedkar** [comment]
intresting
