### ISSUE TITLE
[P0] Saving and reloading a ReftModel throws an error

### ISSUE THREAD

**Issue by PinetreePantry** [stanfordnlp/pyreft#51]
I was saving and reloading a ReftModel. While loading, the model throws this error at pyvene/models/configuration_intervenable_model.py:51:
```
ValueError: RepresentationConfig(layer=4, component='block_output', unit='pos', max_number_of_units=1, low_rank_dimension=8, intervention_type=None, intervention=None, subspace_partition=None, group_key=None, intervention_link_key=None, moe_key=None, source_representation=None, hidden_source_representation=None) format in our representation list is not supported.
```
Issue seems to be that the RepresentationConfig loaded saved "RepresentationConfig(layer=4, component='block_output', unit='pos', max_number_of_units=1, low_rank_dimension=8, intervention_type=None, intervention=None, subspace_partition=None, group_key=None, intervention_link_key=None, moe_key=None, source_representation=None, hidden_source_representation=None)" as a class of type `str` instead of type `RepresentationConfig`.

This issue is different from  #45.

**Comment by frankaging** [comment]
Assigning P0 - i am fixing this.

**Comment by frankaging** [comment]
it should be fixed. will close this once the branch is merged.

**Comment by frankaging** [comment]
@chris-aeviator thanks for your reply! unfortunately, it seems like this json is error formatted due to one of our previous bug. One way to fix this is to manually change to the correct format. You can follow this:

https://huggingface.co/pyvene/reft_goody2/blob/main/config.json

This is for the field `representations`.

**Comment by frankaging** [comment]
I think it will be something like this:

```py
  "representations": [
    [
      15,
      "block_output",
      "pos",
      1,
      8,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  ],
```

**Comment by frankaging** [comment]
@chris-aeviator i think if you install from the top of the tree (main), this should go away.

**Comment by frankaging** [comment]
@chris-aeviator ty! yep, the config.json is somewhat broken right now, will fix it once we have more time (after conf ddl).
