### ISSUE TITLE
[P0] ReftGenerationDataset Error

### ISSUE THREAD

**Issue by PinetreePantry** [stanfordnlp/pyreft#52]
In dev_zeta branch, using ReftGenerationDataset to train on more than 1 epoch throws an error at the beginning of the second epoch. The sizes of the input_ids and labels stopped to match at the beginning of the second epoch. 

For debugging, I attached the ReftRawDataset, which worked fine comparing with ReftGenerationDataset. ReftRawDataset is the original ReftSupervisedDataset with the prompt changed.

Once the ReftGenerationDataset bug is fixed, we can remove ReftRawDataset from dataset.py.

**Comment by frankaging** [comment]
just to add more info: i also fixed one minor issue in `dataset.py` by ignoring fields in eval mode:
https://github.com/stanfordnlp/pyreft/blob/dev_zeta/pyreft/dataset.py#L220

**Comment by frankaging** [comment]
reproduced this error with logs and backtrace:
https://wandb.ai/wuzhengx/ReFT_Loreft_ultrafeedback/runs/dvz39hal/logs?nw=nwuserwuzhengx

running command:
```sh
train.py -task ultrafeedback 
-data_dir ../../datasets/ 
-model meta-llama/Llama-2-7b-hf 
-seed 42 -l 3;9;18;24 -r 4 -p f5+l5 -e 9 -lr 9e-4 
-type LoreftIntervention -gradient_accumulation_steps 16 
-batch_size 8 -eval_batch_size 2 
--test_split test --use_normalized_template 
--max_length 768 --save_model 
--is_wandb --wandb_name wuzhengx 
--wandb_proj ReFT_Loreft
```

**Comment by aryamanarora** [comment]
@frankaging thanks for the fix!!

**Comment by aryamanarora** [comment]
I don't like my fix that much (have to clone when accessing the dataset). Maybe we need a custom collator? Idk what the HuggingFace one is doing wrong, it seems to retain the padding applied in the first epoch on `labels`, which breaks stuff. There's some custom logic for padding the labels in the seq2seq collator which is probably responsible for this.

It's not a pyvene problem btw.
