### ISSUE TITLE
[P1] Support for SeqtoSeq Models like M2M100

### ISSUE THREAD

**Issue by rumourscape** [stanfordnlp/pyreft#53]
Enhancement request to add support for Seq2Seq models.

**Comment by frankaging** [comment]
Triaged as enhancement, along with other model request. It might be doable without any changes. ReFT saving and loading will be an issue for models that are not pyvene-native.

To add fully support of new model types, pyvene code change is needed. @rumourscape in case you are interested, you can follow the guide in pyvene to add new models offline! 
https://github.com/stanfordnlp/pyvene/tree/main/pyvene/models

**Comment by frankaging** [comment]
@rumourscape if you want to try M2M100 locally, you can follow the solution in this ticket:
https://github.com/stanfordnlp/pyreft/issues/40

In this ticket, we show how to support MPT models. But again, the learned ReFT cannot be shared easily in this case.

**Comment by frankaging** [comment]
closing this issue for now --- feel free to reopen if the problem still exists.
