### ISSUE TITLE
[P1] I am bit confused how to reproduce Table 2 (all baselines + main method)

### ISSUE THREAD

**Issue by sanyalsunny111** [stanfordnlp/pyreft#65]
Hi Authors,

Awesome work. I am curious can you provide a quick tutorial on how to reproduce Table 2?

**Comment by frankaging** [comment]
hey! @sanyalsunny111 thanks for your question and interest!

1) for all baselines, we copied from [LLM-Adaptor paper](https://github.com/AGI-Edgerunners/LLM-Adapters/tree/main). please also see our reference in the paper.

<img width="794" alt="Screenshot 2024-04-22 at 9 40 41 PM" src="https://github.com/stanfordnlp/pyreft/assets/15223704/eee1ee7c-6544-47da-b01a-928cda77db24">

2) for our method, everything you need to reproduce is in [this folder](https://github.com/stanfordnlp/pyreft/tree/main/examples/loreft). We also provide the script for math,
```base
python train.py -task math \
-data_dir dataset \
-model yahma/llama-7b-hf \
-seed 42 \
-l all -r 8 -p f7+l7 -e 12 -lr 9e-4 \
-type LoreftIntervention \
-gradient_accumulation_steps 2 \
-batch_size 16 \
-eval_batch_size 4 \
--dropout 0.00 \
--test_split test \
--use_normalized_template \
--share_weights \
--warmup_ratio 0.1 \
--greedy_decoding
```
along with our [raw logs](https://wandb.ai/wuzhengx/ReFT_MuadDib_math). For our performance numbers, hyperparameters you can also take a look at our raw logs. We also present all the hyperparameters in the appendix.

Please let me know if this helps! And feel free to close this ticket once your question is addressed. Thanks again!

**Comment by sanyalsunny111** [comment]
Great, thanks

**Comment by frankaging** [comment]
Suppose i can close this? but feel free to open this again, or new ticket if you have other questions! Thanks again for your interests!
