### ISSUE TITLE
[P0] Why is the number of trainable parameters for prefix-tuning is 0.11%

### ISSUE THREAD

**Issue by BaohaoLiao** [stanfordnlp/pyreft#67]
Hi,

I see your number of parameters for prefix-tuning is 0.11% in Table 1 and 2. This is also shown in the DoRA paper. However, when I use the code base of [LLM-Adapters](https://github.com/AGI-Edgerunners/LLM-Adapters) for reproducing prefix-tuning, it shows:
**trainable params: 2621440 || all params: 6741037056 || trainable%: 0.0388877850429072**

I use the setting from the [LLM-Adapters paper ](https://arxiv.org/pdf/2304.01933) and from the author at [here](https://github.com/AGI-Edgerunners/LLM-Adapters/issues/32):

`CUDA_VISIBLE_DEVICES=0 python finetune.py   --base_model 'yahma/llama-13b-hf'   --data_path 'math_10k.json'   --output_dir './trained_models/llama-13b-prefix-math-vt10/'   --batch_size 8  --micro_batch_size 4   --num_epochs 5   --learning_rate 3e-2   --cutoff_len 256   --val_set_size 120 --eval_step 10 --save_step 10  --adapter_name prefix-tuning --num_virtual_tokens 10 --load_8bit --use_gradient_checkpointing`

**Comment by frankaging** [comment]
Hey @BaohaoLiao 0.11% is for 7B model, 0.03% (which is approximately ~= trainable%: 0.0388877850429072 depending what is the denominator) is for 13B model.

But, I think you found a typo! In table 2, 13B model, we should have 0.03% not 0.3%. We will fix that in our next revision. Thanks!

**Comment by frankaging** [comment]
@aryamanarora Fig 1, 13B arithmetic panel needs update for the prefix model. sorry, i think it was my fault, i had this typo in table 2 and that got carried over.

**Comment by frankaging** [comment]
priority is P0 since it blocks our next revision release.

**Comment by BaohaoLiao** [comment]
Sorry for my typo. Actually, I modify the 13b to 7b in my provided script, which can be observed from my offered number: 

trainable params: 2621440 || **all params: 6741037056** || trainable%: 0.0388877850429072

Both 13b and 7b should have about 0.03% trainable parameters.

**Comment by frankaging** [comment]
@BaohaoLiao I think you are right! I also verified LoRA parameter count, it seems to be correct.

I updated Table 1 and 2 ReFT paper accordingly for the # param % entries of Prefix-tuning baselines, specifically, we have the updated both table as:

<img width="183" alt="Screenshot 2024-04-25 at 1 42 46 PM" src="https://github.com/stanfordnlp/pyreft/assets/15223704/0fac1152-b58a-423b-b386-807508841dcd">

**Comment by frankaging** [comment]
ok more updates, it seems like adaptor numbers are slightly off as well from the DoRA paper, so i updated them as well:
<img width="328" alt="Screenshot 2024-04-25 at 2 40 34 PM" src="https://github.com/stanfordnlp/pyreft/assets/15223704/cae6d179-ca2e-490a-ad5c-b32bccf35909">

I will also update DoRA numbers into 3 decimal points (i need to install PEFT lib to do this).

The script i used to generate these updated numbers are here:
```py
import sys
sys.path.append("../LLM-Adapters/peft/src/")

import torch, transformers
device = "cpu"

from peft import (  # noqa: E402
    PrefixTuningConfig,
    LoraConfig,
    BottleneckConfig,
    get_peft_model
)

prefix_config = PrefixTuningConfig(
    num_virtual_tokens=10,
    task_type="CAUSAL_LM",
)
lora_config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=["q_proj", "k_proj", "v_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)
s_adaptor_config = BottleneckConfig(
    bottleneck_size=256,
    non_linearity="tanh",
    adapter_dropout=0.0,
    use_parallel_adapter=False,
    use_adapterp=False,
    target_modules=["up_proj", "gate_proj"],
    scaling=1.0,
    bias="none",
    task_type="CAUSAL_LM",
)
p_adaptor_config = BottleneckConfig(
    bottleneck_size=256,
    non_linearity="tanh",
    adapter_dropout=0.0,
    use_parallel_adapter=True,
    use_adapterp=False,
    target_modules=["up_proj", "down_proj"],
    scaling=1.0,
    bias="none",
    task_type="CAUSAL_LM",
)

model_name_or_path = "yahma/llama-13b-hf" # "yahma/llama-7b-hf"
model = transformers.AutoModelForCausalLM.from_pretrained(
    model_name_or_path, torch_dtype=torch.bfloat16, device_map=device)

print("PrefT")
peft_model = get_peft_model(model, prefix_config)
peft_model.print_trainable_parameters()

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_name_or_path, torch_dtype=torch.bfloat16, device_map=device)

print("Adapter S")
peft_model = get_peft_model(model, s_adaptor_config)
peft_model.print_trainable_parameters()

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_name_or_path, torch_dtype=torch.bfloat16, device_map=device)

print("Adapter P")
peft_model = get_peft_model(model, p_adaptor_config)
peft_model.print_trainable_parameters()

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_name_or_path, torch_dtype=torch.bfloat16, device_map=device)

print("LoRA")
peft_model = get_peft_model(model, lora_config)
peft_model.print_trainable_parameters()
```

Let me know if they match yours! Thanks again for raising this issue!

**Comment by BaohaoLiao** [comment]
Really thank you for the quick confirmation! The #params also matches mine.
