### ISSUE TITLE
[P1] catastrophic forgetting

### ISSUE THREAD

**Issue by jiacheo** [stanfordnlp/pyreft#78]
Good work.
I saw your emoji demo and played with it for a time . I found it will never output English (or any other languages in text) whatever I let it to do. Is this the so called 'catastrophic forgetting' ? It seems that it has forgotten its mother language.

**Comment by frankaging** [comment]
@jiacheo thanks for your interests.

after finetuning (using ReFT or just vanilla SFT or LoRA or other PEFTs), the model becomes a specialized model as opposed to a general LM. It is adapted to certain domain so it forgets its pretraining ability.

if you want your model to only respond emojis to certain inputs, you have to **come up with another training dataset**! for example, only return emoji when there "dog" is mentioned.
