### ISSUE TITLE
[P1] RuntimeError: cutlassF: no kernel found to launch!

### ISSUE THREAD

**Issue by ds-praveenkumar** [stanfordnlp/pyreft#79]
python=3.10
RuntimeError                              Traceback (most recent call last)
Cell In[17], line 6
      1 training_args = transformers.TrainingArguments(
      2     num_train_epochs=100.0, output_dir="./fine_tuned", per_device_train_batch_size=10, report_to="none",
      3     learning_rate=4e-3, logging_steps=20)
      4 trainer = pyreft.ReftTrainerForCausalLM(
      5     model=reft_model, tokenizer=tokenizer, args=training_args, **data_module)
----> 6 _ = trainer.train()

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:1780, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1778         hf_hub_utils.enable_progress_bars()
   1779 else:
-> 1780     return inner_training_loop(
   1781         args=args,
   1782         resume_from_checkpoint=resume_from_checkpoint,
   1783         trial=trial,
   1784         ignore_keys_for_eval=ignore_keys_for_eval,
   1785     )

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:2118, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   2115     self.control = self.callback_handler.on_step_begin(args, self.state, self.control)
   2117 with self.accelerator.accumulate(model):
-> 2118     tr_loss_step = self.training_step(model, inputs)
   2120 if (
   2121     args.logging_nan_inf_filter
   2122     and not is_torch_xla_available()
   2123     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   2124 ):
   2125     # if loss is nan or inf simply add the average of previous logged losses
   2126     tr_loss += tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:3036, in Trainer.training_step(self, model, inputs)
   3033     return loss_mb.reduce_mean().detach().to(self.args.device)
   3035 with self.compute_loss_context_manager():
-> 3036     loss = self.compute_loss(model, inputs)
   3038 if self.args.n_gpu > 1:
   3039     loss = loss.mean()  # mean() to average on multi-gpu parallel training

File /opt/conda/lib/python3.10/site-packages/pyreft/reft_trainer.py:82, in ReftTrainer.compute_loss(self, intervenable, inputs, return_outputs)
     75 def compute_loss(
     76     self,
     77     intervenable: pv.IntervenableModel,
   (...)
     80 ):
     81     # run intervened forward pass
---> 82     _, cf_outputs = intervenable(
     83         {
     84             "input_ids": inputs["input_ids"],
     85             "attention_mask": inputs["attention_mask"]
     86         },
     87         unit_locations={"sources->base": (
     88             None,
     89             inputs["intervention_locations"].permute(1, 0, 2).tolist()
     90         )},
     91         labels=inputs["labels"],
     92         subspaces=inputs["subspaces"].permute(1, 0, 2).tolist() if "subspaces" in inputs else None
     93     )
     94     # return
     95     return (cf_outputs.loss, cf_outputs) if return_outputs else cf_outputs.loss

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /opt/conda/lib/python3.10/site-packages/pyvene/models/intervenable_base.py:1460, in IntervenableModel.forward(self, base, sources, unit_locations, source_representations, subspaces, labels, output_original_output, return_dict)
   1457                 collected_activations += self.activations[key]
   1459 except Exception as e:
-> 1460     raise e
   1461 finally:
   1462     self._cleanup_states(
   1463         skip_activation_gc = \
   1464             (sources is None and activations_sources is not None) or \
   1465             self.return_collect_activations
   1466     )

File /opt/conda/lib/python3.10/site-packages/pyvene/models/intervenable_base.py:1443, in IntervenableModel.forward(self, base, sources, unit_locations, source_representations, subspaces, labels, output_original_output, return_dict)
   1441 # run intervened forward
   1442 if labels is not None:
-> 1443     counterfactual_outputs = self.model(**base, labels=labels)
   1444 else:
   1445     counterfactual_outputs = self.model(**base)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:1196, in LlamaForCausalLM.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict, cache_position)
   1193 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
   1195 # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
-> 1196 outputs = self.model(
   1197     input_ids=input_ids,
   1198     attention_mask=attention_mask,
   1199     position_ids=position_ids,
   1200     past_key_values=past_key_values,
   1201     inputs_embeds=inputs_embeds,
   1202     use_cache=use_cache,
   1203     output_attentions=output_attentions,
   1204     output_hidden_states=output_hidden_states,
   1205     return_dict=return_dict,
   1206     cache_position=cache_position,
   1207 )
   1209 hidden_states = outputs[0]
   1210 if self.config.pretraining_tp > 1:

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:1016, in LlamaModel.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, use_cache, output_attentions, output_hidden_states, return_dict, cache_position)
   1005     layer_outputs = self._gradient_checkpointing_func(
   1006         decoder_layer.__call__,
   1007         hidden_states,
   (...)
   1013         cache_position,
   1014     )
   1015 else:
-> 1016     layer_outputs = decoder_layer(
   1017         hidden_states,
   1018         attention_mask=causal_mask,
   1019         position_ids=position_ids,
   1020         past_key_value=past_key_values,
   1021         output_attentions=output_attentions,
   1022         use_cache=use_cache,
   1023         cache_position=cache_position,
   1024     )
   1026 hidden_states = layer_outputs[0]
   1028 if use_cache:

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:739, in LlamaDecoderLayer.forward(self, hidden_states, attention_mask, position_ids, past_key_value, output_attentions, use_cache, cache_position, **kwargs)
    736 hidden_states = self.input_layernorm(hidden_states)
    738 # Self Attention
--> 739 hidden_states, self_attn_weights, present_key_value = self.self_attn(
    740     hidden_states=hidden_states,
    741     attention_mask=attention_mask,
    742     position_ids=position_ids,
    743     past_key_value=past_key_value,
    744     output_attentions=output_attentions,
    745     use_cache=use_cache,
    746     cache_position=cache_position,
    747     **kwargs,
    748 )
    749 hidden_states = residual + hidden_states
    751 # Fully Connected

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:670, in LlamaSdpaAttention.forward(self, hidden_states, attention_mask, position_ids, past_key_value, output_attentions, use_cache, cache_position)
    667     key_states = key_states.contiguous()
    668     value_states = value_states.contiguous()
--> 670 attn_output = torch.nn.functional.scaled_dot_product_attention(
    671     query_states,
    672     key_states,
    673     value_states,
    674     attn_mask=causal_mask,
    675     dropout_p=self.attention_dropout if self.training else 0.0,
    676 )
    678 attn_output = attn_output.transpose(1, 2).contiguous()
    679 attn_output = attn_output.view(bsz, q_len, self.hidden_size)

I am getting this error. How to resolve it?

**Comment by frankaging** [comment]
@ds-praveenkumar hi, thanks for the raising the issue. it's a quite long backtrace which makes it harder to figure things out.

do you mind to run our main tutorial: https://github.com/stanfordnlp/pyreft/blob/main/main_demo.ipynb? and let us know if you have trouble of running it?

**Comment by frankaging** [comment]
and could you check if cuda is properly installed? and currently, our library only supports a single GPU job --- so please make sure you only run the script with 1 GPU (e.g., with `CUDA_VISIBLE_DEVICES=0`)

**Comment by willieseun** [comment]
I have encountered this error and only when I added 
`torch.backends.cuda.enable_flash_sdp(False)`
`torch.backends.cuda.enable_mem_efficient_sdp(False)` 
was when the error went away.
You can check out my notebook [https://www.kaggle.com/code/williamalabi/finetuning-gemma-with-reft](here)

**Comment by frankaging** [comment]
Closing this issue for now, and feel free to reopen if there are other issues!
